name: Push-to-EC2

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Set up Infrastructure with Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false -var="aws_access_key=${{ secrets.TF_VAR_aws_access_key }}" -var="aws_secret_key=${{ secrets.TF_VAR_aws_secret_key }}" -var="username=${{ secrets.TF_VAR_username }}" -var="password=${{ secrets.TF_VAR_password }}"

      - name: Apply Terraform
        id: apply
        run: terraform apply -input=false -auto-approve -var="aws_access_key=${{ secrets.TF_VAR_aws_access_key }}" -var="aws_secret_key=${{ secrets.TF_VAR_aws_secret_key }}" -var="username=${{ secrets.TF_VAR_username }}" -var="password=${{ secrets.TF_VAR_password }}"

      - name: Output EC2 Public IP
        id: output_ip
        run: echo "EC2_PUBLIC_IP=$(terraform output -raw public_ip)" >> $GITHUB_ENV

    outputs:
      ec2_public_ip: ${{ steps.output_ip.outputs.EC2_PUBLIC_IP }}

  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Print EC2 Public IP for Debugging
        run: echo "EC2 Public IP is ${{ needs.terraform.outputs.ec2_public_ip }}"

      - name: Executing remote SSH commands using username and password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ needs.terraform.outputs.ec2_public_ip }}
          username: ${{ secrets.TF_VAR_username }}
          password: ${{ secrets.TF_VAR_password }}
          script: |
            sudo apt-get -y update
            sudo apt-get install -y apache2
            sudo systemctl start apache2
            sudo systemctl enable apache2
            cd /home/${{ secrets.TF_VAR_username }}
            sudo mv * /var/www/html
